<?php

namespace App\Repositories\Eloquent;

use App\Models\Admin;
use App\Repositories\Contracts\AdminRepositoryInterface;
use Illuminate\Database\Eloquent\Model;

class AdminRepository extends AbstractRepository implements AdminRepositoryInterface
{

    public function __construct(Admin $admin)
    {
        parent::__construct($admin); // TODO: Change the autogenerated stub
    }

    public function queryList(array $data)
    {
        return $this->model->orderByDesc('id');
    }

    public function changeStatus($id)
    {
        $isActive = 0;
        $admin  = $this->model->findOrFail($id);
        if ($admin->is_active == $isActive){
            $isActive  = 1;
        }
        return $admin->update(['is_active' => $isActive]);
    }
}
