<?php

namespace App\Repositories\Eloquent;

use App\Models\Attribute;
use App\Repositories\Contracts\AttributeRepositoryInterface;
use App\Repositories\Contracts\UserRepositoryInterface;
use Illuminate\Database\Eloquent\Model;

class AttributeRepository extends AbstractRepository implements AttributeRepositoryInterface
{

    public function __construct(Attribute $attribute)
    {
        parent::__construct($attribute); // TODO: Change the autogenerated stub
    }

    public function queryList(array $data)
    {
        return $this->model->query()
            ->when(!empty($data['name']), function ($query) use ($data) {
                $query->where('name', 'like', '%' . $data['name'] . '%');
            })->orderByDesc('id');
    }

}
