<?php

namespace App\Repositories\Eloquent;


use App\Models\Banner;
use App\Repositories\Contracts\BannerRepositoryInterface;
use Illuminate\Database\Eloquent\Model;

class BannerRepository extends AbstractRepository implements BannerRepositoryInterface
{

    public function __construct(Banner $banner)
    {
        parent::__construct($banner); // TODO: Change the autogenerated stub
    }

    public function queryList(array $data)
    {
        return $this->model->orderByDesc('id');
    }

    public function changeStatus($id)
    {
        $is_active = 0;
        $banner = $this->model->findOrFail($id);
        if ($banner->is_active == $is_active){
            $is_active = 1;
        }
        return $banner->update(['is_active'=>$is_active]);
    }

    public function incrementOrder($order)
    {
        return $this->model->where('order', '>=', $order)->increment('order');
    }
}
