<?php

namespace App\Repositories\Eloquent;

use App\Models\Media;
use App\Models\User;
use App\Repositories\Contracts\MediaRepositoryInterface;
use App\Repositories\Contracts\UserRepositoryInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class MediaRepository extends AbstractRepository implements MediaRepositoryInterface
{

    public function __construct(Media $media)
    {
        parent::__construct($media); // TODO: Change the autogenerated stub
    }

    public function uploadFile($file, $folder)
    {
        $path = null;
        if (is_file($file)) {
            $path = Storage::disk('public')->put($folder, $file);
        }
        return $path;
    }
}
